import { type Article } from '@/components/ArticleCard'

// Immagine placeholder motorsport (sostituita da Sanity in produzione)
const PLACEHOLDER = 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80'
const PLACEHOLDER_2 = 'https://images.unsplash.com/photo-1541447270886-5b0a95c8f8ea?w=800&q=80'
const PLACEHOLDER_3 = 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&q=80'

// Articoli mostrati in hero + "Le ultime news"
export const MOCK_ARTICLES: Article[] = [
  {
    id: '1',
    title: 'Camara sull\'annuncio di Haas: "Contento di prendere il posto ad Ocon"',
    slug: 'formula-1/camara-haas-ocon',
    category: 'Formula 1',
    author: 'Francesco Di Blasi',
    date: '28 maggio',
    imageUrl: PLACEHOLDER,
    breaking: true,
    excerpt: 'Il pilota brasiliano prenderà il volante della seconda Haas dal prossimo campionato: le prime parole dopo l\'ufficialità.',
    content: [
      { type: 'paragraph', text: 'L\'annuncio è arrivato nella mattinata di martedì e ha chiuso settimane di indiscrezioni: Gabriel Camara sarà il compagno di squadra in Haas a partire dalla prossima stagione, prendendo il posto lasciato libero da Esteban Ocon.' },
      { type: 'paragraph', text: 'Il pilota brasiliano, reduce da una stagione di Formula 2 chiusa nelle prime posizioni del campionato, ha commentato la notizia con un misto di entusiasmo e consapevolezza della sfida che lo attende: "È il momento più importante della mia carriera. So che Haas mi sta dando una possibilità che in pochi ottengono, e voglio ripagarla con il lavoro."' },
      { type: 'paragraph', text: 'Il team principal ha spiegato che la scelta è arrivata dopo un lungo processo di valutazione che ha coinvolto sessioni al simulatore e diversi test privati con la vettura del 2025, in cui Camara avrebbe convinto per costanza di rendimento più che per il singolo giro veloce.' },
      { type: 'image', src: PLACEHOLDER_2, caption: 'Gabriel Camara durante un test privato con la vettura Haas' },
      { type: 'paragraph', text: 'Non sono mancate le voci critiche, legate soprattutto alla scarsa esperienza del brasiliano nelle categorie propedeutiche europee. Camara ha risposto a modo suo, ricordando come il suo percorso — cresciuto lontano dai circuiti tradizionali del motorsport continentale — sia già di per sé un caso studio.' },
      { type: 'paragraph', text: 'Resta da capire come si evolverà il resto della griglia piloti Haas per la prossima stagione, con il team che ha lasciato intendere di voler sciogliere le riserve sul secondo sedile solo dopo la pausa estiva.' },
      { type: 'paragraph', text: 'Intanto la reazione dei tifosi sui social è stata in larga parte positiva, con molti che sottolineano il coraggio della scelta in un mercato piloti sempre più conservativo, orientato verso nomi già affermati piuttosto che verso le nuove leve.' },
      { type: 'paragraph', text: 'Camara avrà a disposizione le prossime settimane per iniziare il lavoro di preparazione fisica e tecnica insieme al team, in vista dei primi test collettivi in programma alla fine della stagione corrente.' },
    ],
  },
  {
    id: '2',
    title: 'Hamilton alla Ferrari: le prime impressioni dopo i test di Barcellona',
    slug: 'formula-1/hamilton-ferrari-barcellona',
    category: 'Formula 1',
    author: 'Redazione',
    date: '27 maggio',
    imageUrl: PLACEHOLDER_2,
    breaking: true,
  },
  {
    id: '3',
    title: 'Verstappen: "La Red Bull ha ancora margine di sviluppo"',
    slug: 'formula-1/verstappen-red-bull-sviluppo',
    category: 'Formula 1',
    author: 'Luca Rossi',
    date: '26 maggio',
    imageUrl: PLACEHOLDER_3,
  },
  {
    id: '4',
    title: 'WEC Le Mans: Ferrari in pole position con la 499P',
    slug: 'wec/ferrari-le-mans-pole',
    category: 'WEC',
    author: 'Marco Bianchi',
    date: '25 maggio',
    imageUrl: PLACEHOLDER,
  },
  {
    id: '5',
    title: 'Formula 2: Antonelli domina in qualifica a Monaco',
    slug: 'formula-2/antonelli-monaco-qualifica',
    category: 'Formula 2',
    author: 'Francesco Di Blasi',
    date: '24 maggio',
    imageUrl: PLACEHOLDER_2,
  },
  {
    id: '6',
    title: 'Norris: "McLaren è pronta a lottare per il titolo fino alla fine"',
    slug: 'formula-1/norris-mclaren-titolo',
    category: 'Formula 1',
    author: 'Luca Rossi',
    date: '23 maggio',
    imageUrl: PLACEHOLDER_3,
  },
  {
    id: '11',
    title: 'Leclerc: "Il passo gara della Ferrari è cresciuto molto nelle ultime settimane"',
    slug: 'formula-1/leclerc-passo-gara-ferrari',
    category: 'Formula 1',
    author: 'Redazione',
    date: '22 maggio',
    imageUrl: PLACEHOLDER,
  },
  {
    id: '12',
    title: 'Russell: "Mercedes può ancora giocarsi il mondiale costruttori"',
    slug: 'formula-1/russell-mercedes-mondiale-costruttori',
    category: 'Formula 1',
    author: 'Marco Bianchi',
    date: '21 maggio',
    imageUrl: PLACEHOLDER_2,
  },
]

// Articoli aggiuntivi per la sezione "Altre News" — non compaiono in
// hero/"Le ultime news", così la sezione mostra contenuti diversi.
// Da sostituire con la query Sanity reale quando il CMS sarà collegato.
export const MOCK_OTHER_ARTICLES: Article[] = [
  {
    id: '7',
    title: 'WRC Rally Italia Sardegna: doppietta Toyota, ordine ribaltato nel finale',
    slug: 'wrc/rally-italia-sardegna-toyota',
    category: 'WRC',
    author: 'Marco Bianchi',
    date: '22 maggio',
    imageUrl: PLACEHOLDER_3,
  },
  {
    id: '8',
    title: 'Formula 3: pole position per il rookie italiano a Barcellona',
    slug: 'formula-3/pole-rookie-italiano-barcellona',
    category: 'Formula 3',
    author: 'Redazione',
    date: '21 maggio',
    imageUrl: PLACEHOLDER,
  },
  {
    id: '9',
    title: 'Mercedes annuncia il rinnovo dello sponsor titolo per il 2026',
    slug: 'formula-1/mercedes-rinnovo-sponsor-2026',
    category: 'Formula 1',
    author: 'Francesco Di Blasi',
    date: '20 maggio',
    imageUrl: PLACEHOLDER_2,
  },
  {
    id: '10',
    title: 'MotoGP a Barcellona: analisi del weekend e classifica aggiornata',
    slug: 'altro/motogp-barcellona-analisi',
    category: 'Altro',
    author: 'Luca Rossi',
    date: '19 maggio',
    imageUrl: PLACEHOLDER_3,
  },
  {
    id: '13',
    title: 'WEC: Toyota risponde a Ferrari nei test privati di Portimao',
    slug: 'wec/toyota-test-portimao',
    category: 'WEC',
    author: 'Marco Bianchi',
    date: '18 maggio',
    imageUrl: PLACEHOLDER,
  },
  {
    id: '14',
    title: 'Formula 2: cambio di rotta tecnico per il team Prema in vista di Barcellona',
    slug: 'formula-2/prema-cambio-tecnico-barcellona',
    category: 'Formula 2',
    author: 'Francesco Di Blasi',
    date: '17 maggio',
    imageUrl: PLACEHOLDER_2,
  },
  {
    id: '15',
    title: 'WRC: la Hyundai presenta gli aggiornamenti in vista del Rally di Sardegna',
    slug: 'wrc/hyundai-aggiornamenti-sardegna',
    category: 'WRC',
    author: 'Redazione',
    date: '16 maggio',
    imageUrl: PLACEHOLDER_3,
  },
  {
    id: '16',
    title: 'Formula 1: la FIA conferma il nuovo regolamento tecnico per il 2027',
    slug: 'formula-1/fia-regolamento-tecnico-2027',
    category: 'Formula 1',
    author: 'Luca Rossi',
    date: '15 maggio',
    imageUrl: PLACEHOLDER,
  },
  {
    id: '17',
    title: 'Formula 3: Barcellona, tripletta italiana nelle libere del venerdì',
    slug: 'formula-3/tripletta-italiana-barcellona',
    category: 'Formula 3',
    author: 'Redazione',
    date: '14 maggio',
    imageUrl: PLACEHOLDER_2,
  },
  {
    id: '18',
    title: 'WEC: Porsche annuncia la line-up 2027 con due piloti esordienti',
    slug: 'wec/porsche-line-up-2027',
    category: 'WEC',
    author: 'Marco Bianchi',
    date: '13 maggio',
    imageUrl: PLACEHOLDER_3,
  },
  {
    id: '19',
    title: 'Formula 2: Barcellona, penalità per due piloti dopo l\'incidente in gara 1',
    slug: 'formula-2/penalita-incidente-gara1-barcellona',
    category: 'Formula 2',
    author: 'Francesco Di Blasi',
    date: '12 maggio',
    imageUrl: PLACEHOLDER,
  },
  {
    id: '20',
    title: 'Formula 1: Aston Martin porta un pacchetto di aggiornamenti a Barcellona',
    slug: 'formula-1/aston-martin-aggiornamenti-barcellona',
    category: 'Formula 1',
    author: 'Luca Rossi',
    date: '11 maggio',
    imageUrl: PLACEHOLDER_2,
  },
  {
    id: '21',
    title: 'WRC: cambio programma per il Rally di Sardegna, ecco i nuovi orari',
    slug: 'wrc/rally-sardegna-nuovi-orari',
    category: 'WRC',
    author: 'Redazione',
    date: '10 maggio',
    imageUrl: PLACEHOLDER_3,
  },
  {
    id: '22',
    title: 'MotoGP: Barcellona, Marquez firma la pole davanti a Bagnaia',
    slug: 'altro/motogp-barcellona-pole-marquez',
    category: 'Altro',
    author: 'Marco Bianchi',
    date: '9 maggio',
    imageUrl: PLACEHOLDER,
  },
  {
    id: '23',
    title: 'Formula 1: Sainz e la Williams, primi segnali di crescita a metà stagione',
    slug: 'formula-1/sainz-williams-crescita-meta-stagione',
    category: 'Formula 1',
    author: 'Francesco Di Blasi',
    date: '8 maggio',
    imageUrl: PLACEHOLDER_2,
  },
  {
    id: '24',
    title: 'Formula 3: cambio regole per il 2027, meno gare ma weekend più lunghi',
    slug: 'formula-3/cambio-regole-2027',
    category: 'Formula 3',
    author: 'Redazione',
    date: '7 maggio',
    imageUrl: PLACEHOLDER_3,
  },
  {
    id: '25',
    title: 'WEC: Ferrari conferma il programma di test privati prima di Fuji',
    slug: 'wec/ferrari-test-privati-fuji',
    category: 'WEC',
    author: 'Marco Bianchi',
    date: '6 maggio',
    imageUrl: PLACEHOLDER,
  },
  {
    id: '26',
    title: 'Formula 1: Alpine valuta un cambio nel muretto box per il 2027',
    slug: 'formula-1/alpine-cambio-muretto-box-2027',
    category: 'Formula 1',
    author: 'Luca Rossi',
    date: '5 maggio',
    imageUrl: PLACEHOLDER_2,
  },
]
