// Descrizioni Instagram vere di @lastcorner_net, divise per tipo di post,
// usate come esempi di stile da "Genera descrizione"
// (app/grafiche/descrizione/route.ts). Il modello imita meglio da esempi
// reali che da regole. Raccolte il 10 ottobre 2026 dagli ultimi 117 post
// (alcune accorciate, refusi degli hashtag corretti): per aggiornarle basta
// sostituire i testi, tenendo 2-4 esempi per tipo.

import type { TipoPost } from '@/lib/ai/tipiPost'

export const ESEMPI_PER_TIPO: Record<TipoPost, string[]> = {
  "risultato": [
    "🇸🇬🏁 VERSTAPPEN SI PRENDE LA SPRINT POLE A SINGAPORE!\n\nPoi Russell e Leclerc, con Ferrari beffata dopo aver dominato il Q3. Solo sesto Hamilton, che pasticcia nel suo giro.\n\n#F1 #F12026 #SingaporeGP",
    "🏁🇸🇬 George Russell chiude in testa la prima ed unica sessione di prove libere a Singapore.\n\nIl britannico precede di due decimi Leclerc e Norris. A +0.5 Hamilton (che ha commesso un errore nell'ultimo giro lanciato) e Piastri.\n\nPiù in difficoltà, almeno per ora, la Red Bull.\n\nAppuntamento alle 14:30 per le qualifiche 👀\n\n#F1 #F12026 #SingaporeGP",
    "🏁🇲🇾 VERSTAPPEN VINCE UNA GARA INFINITA A SEPANG!\n\nSecondo Antonelli, terzo Hamilton, quarto Leclerc, con entrambi i Ferrari che erano in fondo dopo i primi giri.\n\nFuori Russell per un problema alla PU negli ultimi giri!\n\n#F1 #F12026 #BahrainGP",
    "🏁🇲🇾 Leclerc chiude davanti a tutti le libere 2 a Sepang!\n\nFerrari è sembrata molto solida specialmente nelle mani del monegasco sia in simulazione qualifica che nel passo gara.\n\nVicini però gli altri: secondo Hadjar, terzo Norris ad un decimo. Verstappen quarto, ma non ha effettuato l'ultimo tentativo su soft. L'olandese era davanti a tutti dopo lo stint su medie.\n\nP5 per Hamilton; P7 e P8 per le due Mercedes, che non si sono migliorate su soft ma che sono state solide in simulazione gara.\n\n#F1 #F12026 #BahrainGP"
  ],
  "dichiarazioni": [
    "C'è un po' di delusione Leclerc dopo la quinta piazza - che diventerà quarta domani al via - conquistata al termine delle qualifiche a Sepang.\n\nCharles, a detta sua, ha pagato l'evoluzione della pista tra Q1 e Q3, a causa della quale si è trovato sempre più in difficoltà col posteriore nelle fasi finali del giro.\n\n\"Il distacco da Lewis? Penso che abbia semplicemente messo insieme un giro straordinario e che sia riuscito a far quadrare tutto, quindi bravo lui. Da parte mia, credo di aver valutato male l'evoluzione da Q1 a Q3\", ha detto.\n\n\"A me piacciono le macchine con molto avantreno, ma una volta arrivati al Q3, quando spingevo forte nel primo settore, nei settori 2 e 3 perdevo tanto grip al posteriore\".\n\n\"Se si può sperare nel podio? Decisamente sì, tutto ciò che abbiamo visto finora ci dà motivo di sperare che saremo competitivi in termini di passo domani\".\n\nCharles ha concluso parlando di Mercedes, in difficoltà col nuovo pacchetto di aggiornamenti: \"Gli unici un po' più difficili da decifrare sono le Mercedes\".\n\n#F1 #F12026 #FerrariF1 #ScuderiaFerrari #Leclerc",
    "Intervistato da Sky Sport F1 al termine del GP di oggi, Fred Vasseur non ha nascosto un certo disappunto per il risultato della sua squadra.\n\nOltre alla delusione di un passo gara al di sotto delle aspettative, il manager francese si è detto non completamente soddisfatto anche dell'esecuzione.\n\n\"Dopo il secondo posto di ieri ci aspettavamo di meglio. Sul giro secco il passo non era male, potevamo lottare con la Red Bull. Ma fin da inizio gara perdevamo una posizione per giro, era troppo\", ha detto.\n\n\"E alla fine, anche se il passo era comunque discreto, non potevamo superare: eravamo sempre sulla difensiva e in difficoltà. È stato un weekend difficile\".\n\nE sull'esecuzione: \"Ora dobbiamo capire anche cosa avremmo potuto fare meglio questo weekend, perché penso che avremmo potuto fare un lavoro migliore\".\n\n\"Però abbiamo comunque fatto più punti della McLaren per il campionato, e questo ha un peso, anche se l'obiettivo è vincere gare e lottare per il campionato\", ha concluso.\n\n#F1 #F12026 #FerrariF1 #ScuderiaFerrari #AzerbaijanGP",
    "Leclerc non fa proclami nel media day a Singapore: nonostante l'assenza di lunghi rettilinei - notoriamente il tallone d'achille della SF-26 - sul tracciato di Marina Bay, il monegasco non si sente il favorito per il fine settimana.\n\n\"È sicuramente una di quelle piste in cui il layout sembra essere favorevole per noi\", ha detto.\n\n\"Se questo pagherà o meno? Budapest e Monaco sulla carta erano piste adatte a noi, e le cose non sono andate bene. Mentre Silverstone sulla carta era un tracciato ostico per noi, ed è andata davvero benissimo\".\n\n\"Storicamente siamo sempre stati piuttosto forti qui, ma non possiamo affidarci al passato\".\n\n#F1 #F12026 #FerrariF1 #ScuderiaFerrari",
    "Così Max Verstappen sullo stile di guida \"imposto\" dal nuovo regolamento a partire da quest'anno...\n\nPareri? 🤔\n\n#F1 #F12026 #MaxVerstappen #RedBullRacing"
  ],
  "indiscrezione": [
    "😬 Come riportato da Thomas Maher, la bandiera rossa della SQ1 avrebbe causato una serie di problemi ad alcuni team relativamente alla modalità overtake.\n\nL'overtake sarebbe stato reso disponibile solo ad alcune vetture e non ad altre, con inevitabili conseguenze sugli esiti della sessione.\n\n\"Confusione nel paddock: sembra che l'overtake mode sia stata resa disponibile solo per alcuni piloti durante la SQ1, e non per altri\", scrive Maher.\n\n\"La bandiera rossa ha apparentemente innescato problemi per diversi team, portando a erogazioni di potenza disomogenee nella SQ1. Resta da capire se siano in arrivo eventuali reclami...\"\n\n#F1 #F12026 #SingaporeGP",
    "C'è quasi del clamoroso in quanto riportato da Matteo Bobbi durante le FP1 del Gran Premio d'Azerbaijan. Secondo l'autorevole voce di Sky Sport, Leclerc avrebbe montato dischi e pastiglie di Brembo.\n\nIl monegasco, lo ricordiamo, aveva avuto molte difficoltà con i prodotti della casa italiana all'inizio della stagione, culminate con l'incidente a Monaco che lo portò a cambiare a favore di Carbon Industries.\n\nOra, sembrerebbe che ci sia stato un ulteriore cambio di rotta. Lo scoop tuttavia non è stato confermato da Rosario Giuliana, giornalista molto vicino alle vicende del cavallino.\n\n#F1 #F12026 #Leclerc #FerrariF1 #AzerbaijanGP",
    "Come riportato da AutoRacer in una recente live YouTube, Ferrari dovrebbe portare ad Austin quello che sarà \"il pacchetto di aggiornamenti più grande della stagione\".\n\nIn termini di pezzi, sarebbe superiore anche a quello portato da Mercedes in Malesia.\n\nQuesto non è necessariamente sinonimo di performance: Mercedes e McLaren sembrano aver steccato i rispettivi ultimi pacchetti, mentre la stessa Ferrari non ha ottenuto i guadagni attesi con i pezzi di Zandvoort.\n\n#F1 #F12026 #FerrariF1 #ScuderiaFerrari",
    "🚨🚨 Secondo quanto riportato da Thomas Maher sul proprio profilo X, l'investigazione riguardo il sorpasso di Verstappen nei confronti di Hamilton in regime di bandiera gialla si sarebbe conclusa.\n\nLa decisione della FIA sarebbe quella di NON penalizzare l'olandese. Attendiamo il comunicato ufficiale che, al momento, non è ancora arrivato.\n\n#F1 #F12026 #Verstappen #FerrariF1 #Hamilton"
  ],
  "ufficiale": [
    "🚨 Ora è ufficiale: Hadjar torna in Red Bull a partire dall'appuntamento di questo fine settimana a Baku.\n\nIl francese aveva saltato tre tappe per via di un (presunto) infortunio al polso.\n\nContestualmente, Lawson torna in Racing Bulls al posto di Tsunoda che l'aveva sostituito.\n\n#F1 #F12026 #RedBullF1 #Hadjar",
    "🚨🚨 Ci pensa Ferrari a spegnere i rumors che si erano creati in questi giorni riguardo il futuro di Vasseur in Ferrari.\n\nI vertici del Cavallino hanno convocato un incontro coi media per ribadire ancora una volta la fiducia nel team principal francese:\n\n\"Ci sono state parecchie speculazioni intorno alla Scuderia e alla sua leadership\", è stato spiegato nell'incontro, come riportato da Roberto Chinchero per Motorsport.com.\n\n\"La posizione della Ferrari è chiara e non è cambiata. Ferrari ha fatto delle scelte e la fiducia in Fred Vasseur e nel suo team c'era e continua ad esserci\".\n\nQuestione chiusa dunque? Staremo a vedere se la presa di posizione della società contribuirà a ritrovare la serenità necessaria per chiudere la stagione in modo positivo.\n\n#F1 #F12026 #FerrariF1 #ScuderiaFerrari"
  ]
}
