// Descrizioni Instagram vere di @lastcorner_net, usate come esempi di stile
// da "Genera descrizione" (app/grafiche/descrizione/route.ts). Il modello
// imita meglio da esempi reali che da regole: per aggiornarle basta
// sostituire i testi (meglio se di tipo diverso: risultati, dichiarazioni,
// indiscrezioni, analisi, amarcord). Raccolte il 9 ottobre 2026.

export const ESEMPI_DESCRIZIONI: string[] = [
  "📊 Gli aggiornamenti di Baku sembrano aver messo una pezza importante sui punti deboli della Red Bull.\n\nNella sprint quali di Singapore Verstappen si dimostra fortissimo anche nel lento, tenendo testa anche nel secondo settore a due vetture come la SF26 e la W17, notoriamente superiori su questo aspetto fino qualche weekend fa.\n\nLa curva di perdita di Leclerc si gonfia praticamente ad ogni allungo, e non solo nei - pochi - rettilinei del tracciato di Marina Bay.\n\nCharles ricuce con un ottimo settore centrale e con delle staccate assai tardive - specialmente rispetto a Verstappen - ma non è comunque abbastanza per sopperire allo spunto di Red Bull e di Max nel finale.\n\nRussell col pacchetto vecchio è un po' una via di mezzo tra i due, con una vettura decisamente più bilanciata rispetto al compagno di squadra. Attendiamo il termine del weekend per dare sentenze, ma per il momento la squadra di Wolff sembra aver steccato con le novità della Malesia.\n\nHamilton, dal canto suo, aveva portato a casa un ottimo primo settore, se comparato con quello di Leclerc.\n\nLewis paga i tanti snap nel tratto centrale, che potrebbero aver influenzato anche la distribuzione dell'energia nel corso del giro: Leclerc è più veloce (e non di poco) in tutti gli allunghi dell'ultimo settore, costruendo lì tutto il gap sull'inglese.\n\nPartenza e colpi di scena esclusi, difficilmente assisteremo a scambi di posizione domani nella sprint.\n\nPiù interessante è la situazione in vista delle qualifiche, coi team che potranno tornare ad intervenire sul setup: vedremo se qualcuno riuscirà a fermare un Verstappen che per il secondo weekend di fila vola sulle ali dell'entusiasmo\n\n🔗 | L'articolo completo su Lastcorner.net\n\n#F1 #F12026 #ScuderiaFerrari #LewisHamilton #CharlesLeclerc",
  "Nonostante la pole sfumata proprio nel finale, Leclerc non si è detto rammaricato al termine della sprint qualifying a Singapore.\n\nIl monegasco è soddisfatto del giro finale e non crede che il cambio di passo dei rivali fosse dovuto al passaggio da media a soft:\n\n\"Penso di aver guadagnato il tempo sul giro che dovevamo guadagnare con la soft\". \n\n\"Gli altri avevano un piano di uscita leggermente diverso, credo abbiano fatto due giri di raffreddamento mentre noi ne abbiamo fatto solo uno, ma onestamente non credo che questa debba essere una scusa\". \n\nPer Charles, Ferrari non è più al livello dei migliori da un po' di weekend: \"Da tre o quattro gare a questa parte abbiamo perso un po' delle nostre prestazioni assolute e non siamo abbastanza veloci da poter lottare con loro, non ancora\". \n\n\"Sento comunque che c'è potenziale nella vettura e per domani, magari con qualche affinamento, possiamo essere lì a giocarcela per la pole. Non è andata malissimo, ma ci manca ancora qualcosina\". \n\nE sulla sprint: \"Su una pista del genere vorresti scattare dalla prima posizione, superare sarà molto complicato. Vedremo, ma alla fine si tratta solo della Sprint Race: il lavoro vero dovremo farlo domani in qualifica\".\n\n#F1 #F12026 #Leclerc #FerrariF1 #ScuderiaFerrari",
  "\"Verstappen ha spiegato che era sul gas in uscita da curva 7 quando ha visto la bandiera gialla e ha alzato il piede. Ciò è stato confermato dalla telemetria. Entro circa 40 metri dall'ingresso nel settore in regime di bandiera gialla, Verstappen aveva completamente rilasciato l'acceleratore\".\n\n\"Hamilton era in frenata e aveva ridotto la velocità a meno di 60 km/h nel punto in cui Verstappen ha effettuato il sorpasso. Poiché Verstappen era in un giro lanciato e accelerava in uscita da curva 7, mentre Hamilton aveva rallentato, la differenza di velocità al momento dell'affiancamento era notevole, nonostante anche Verstappen avesse iniziato a frenare\".\n\n\"I Commissari hanno ritenuto che Verstappen abbia reagito in modo appropriato alla bandiera gialla, alzando il piede dall'acceleratore e riducendo la velocità\".\n\n\"Verstappen ha chiarito che, per evitare il sorpasso, avrebbe dovuto effettuare una frenata estremamente violenta, manovra che a suo giudizio avrebbe potuto potenzialmente generare una situazione di pericolo\".\n\n\"I Commissari hanno stabilito che Verstappen ha violato il regolamento relativo alle bandiere gialle sorpassando Hamilton. Tuttavia, i Commissari hanno ritenuto che il sorpasso sia stato una sfortunata conseguenza della notevole differenza di velocità e, date le circostanze, hanno deciso di non infliggere alcuna penalità\".\n\nQuesta la giustificazione dei commissari in merito alla decisione di non dare penalità a Max Verstappen per il sorpasso in regime di bandiera gialla a Lewis Hamilton.\n\n#F1 #F12026 #FerrariF1 #ScuderiaFerrari #Verstappen",
  "🚨🚨 Secondo quanto riportato da Thomas Maher sul proprio profilo X, l'investigazione riguardo il sorpasso di Verstappen nei confronti di Hamilton in regime di bandiera gialla si sarebbe conclusa.\n\nLa decisione della FIA sarebbe quella di NON penalizzare l'olandese. Attendiamo il comunicato ufficiale che, al momento, non è ancora arrivato.\n\n#F1 #F12026 #Verstappen #FerrariF1 #Hamilton",
  "😬 Come riportato da Thomas Maher, la bandiera rossa della SQ1 avrebbe causato una serie di problemi ad alcuni team relativamente alla modalità overtake.\n\nL'overtake sarebbe stato reso disponibile solo ad alcune vetture e non ad altre, con inevitabili conseguenze sugli esiti della sessione.\n\n\"Confusione nel paddock: sembra che l'overtake mode sia stata resa disponibile solo per alcuni piloti durante la SQ1, e non per altri\", scrive Maher.\n\n\"La bandiera rossa ha apparentemente innescato problemi per diversi team, portando a erogazioni di potenza disomogenee nella SQ1. Resta da capire se siano in arrivo eventuali reclami...\"\n\n#F1 #F12026 #SingaporeGP",
  "🇸🇬🏁 VERSTAPPEN SI PRENDE LA SPRINT POLE A SINGAPORE!\n\nPoi Russell e Leclerc, con Ferrari beffata dopo aver dominato il Q3. Solo sesto Hamilton, che pasticcia nel suo giro.\n\n#F1 #F12026 #SingaporeGP",
  "🏁🇸🇬 George Russell chiude in testa la prima ed unica sessione di prove libere a Singapore.\n\nIl britannico precede di due decimi Leclerc e Norris. A +0.5 Hamilton (che ha commesso un errore nell'ultimo giro lanciato) e Piastri. \n\nPiù in difficoltà, almeno per ora, la Red Bull.\n\nAppuntamento alle 14:30 per le qualifiche 👀\n\n#F1 #F12026 #SingaporeGP",
  "🔙🇸🇬 Singapore 2017: il weekend che doveva riportarlo in testa in classifica si trasforma in un incubo per Vettel:\n\nIl tedesco, che aveva conquistato con margine la pole al sabato, si rese protagonista di quel famigerato incidente al via con Verstappen e Raikkonen (nel quale venne coinvolto anche l'incolpevole Alonso).\n\nAd approfittarne fu Hamilton, uscito indenne da curva 1. Lewis vinse e si portò a +28 in classifica, consolidando la leadership di un mondiale che avrebbe vinto di lì a poco.\n\n#F1 #F12026 #Vettel #SingaporeGP",
  "Leclerc non fa proclami nel media day a Singapore: nonostante l'assenza di lunghi rettilinei - notoriamente il tallone d'achille dell SF-26 - sul tracciato di Marina Bay, il monegasco non si sente il favorito per il fine settimana.\n\n\"È sicuramente una di quelle piste in cui il layout sembra essere favorevole per noi\", ha detto. \n\n\"Se questo pagherà o meno? Budapest e Monaco sulla carta erano piste adatte a noi, e le cose non sono andate bene. Mentre Silverstone sulla carta era un tracciato ostico per noi, ed è andata davvero benissimo\". \n\n\"Non so se questo basti a dare un quadro completo, ma di certo daremo il massimo\".\n\n\"Storicamente siamo sempre stati piuttosto forti qui, ma non possiamo affidarci al passato\".\n\n\"È anche vero che ultimamente la tendenza è stata quella di perdere un po' di prestazioni rispetto a chi sta davanti, quindi vincere sarà una sfida enorme. Sarà davvero difficile\".\n\n#F1 #F12026 #FerrariF1 #ScuderiaFerrari",
  "Come riportato da AutoRacer in una recente live YouTube, Ferrari dovrebbe portare ad Austin quello che sarà \"il pacchetto di aggiornamenti più grande della stagione\".\n\nIn termini di pezzi, sarebbe superiore anche a quello portato da Mercedes in Malesia.\n\nQuesto non è necessariamente sinonimo di performance: Mercedes e McLaren sembrano aver steccato i rispettivi ultimi pacchetti, mentre la stessa Ferrari non ha ottenuto i guadagni attesi con i pezzi di Zandvoort.\n\n#F1 #F12026 #FerrariF1 #ScuderiaFerrari",
  "👀🇸🇬 Mercedes, McLaren, Ferrari e Red Bull si sono divise le vittorie delle ultime quindici edizioni del GP di Singapore\n\nLo scorso anno fu Russell a trionfare; l'ultima vittoria Ferrari risale al 2023, con quella masterclass tattica di Sainz. La Rossa ha vinto anche nel 2015 e nel 2010 rispettivamente con Vettel ed Alonso.\n\nQuello di Marina Bay è uno dei pochissimi tracciati sui quali Verstappen non ha ancora vinto: staremo a vedere se l'olandese riuscirà a bissare il successo della Malesia questo fine settimana 👀\n\n#F1 #F12026 #SingaporeGP",
  "😬 Verstappen non sembra particolarmente interessato alla destinazione Ferrari, quantomeno per il momento.\n\n\"Voglio solo vincere, non sono un tipo nostalgico\", ha detto l'olandese in un'intervista riportata da Sky Sports F1. \n\n\"Ho molto rispetto per Ferrari? Assolutamente sì. Ma se questo significa impegnarsi per poi ritrovarsi a lottare per il quinto o sesto posto, che senso ha?\"\n\n\"Sono fortemente orientato alle prestazioni e ho già vinto tantissimo con questa squadra. La Red Bull è una seconda famiglia, e la sfida della sua ricostruzione è ciò che mi stimola a dare il massimo\".\n\n#F1 #F12026 #Verstappen #FerrariF1 #ScuderiaFerrari"
]
